=== flagada08/Aion-emu_project_1.9/AE-go_GameServer/data/static_data/quest_script_data/quest_script_data.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="../quest_data/quest_data.xsd" />
	<xs:include schemaLocation="../import.xsd" />
	
	<xs:element name="quest_scripts" type="QuestScripts" />
	
	<xs:complexType name="QuestScripts">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="item_collecting" type="ItemCollectingData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="report_to" type="ReportToData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="monster_hunt" type="MonsterHuntData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="work_order" type="WorkOrdersData" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="QuestScriptData" abstract="true" >
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>
	
	<xs:complexType name="ItemCollectingData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="action_item_id" type="xs:int" default="0"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ReportToData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="item_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MonsterHuntData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="monster_infos" type="MonsterInfos" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MonsterInfos" >
		<xs:attribute name="var_id" type="xs:int" use="required"/>
		<xs:attribute name="max_kill" type="xs:int" use="required"/>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="WorkOrdersData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="give_component" type="QuestItems" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="recipe_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== flagada08/Aion-emu_project_1.9/AE-go_GameServer/data/static_data/quest_script_data/poeta.xml
<quest_scripts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quest_script_data.xsd">
<!--
  ~ This file is part of aion-unique.
  ~
  ~ aion-unique is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ aion-unique is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with aion-unique.  If not, see <http://www.gnu.org/licenses/>.
  -->

<!-- Start Poeta http://www.aionarmory.com/search.aspx?browse=4.3.1#quests:0+2+1 -->
	
	<!-- Kalio's Call handled by script -->
	<!-- Kerubar Hunt -->
	<monster_hunt id="1102" start_npc_id="203057">
		<monster_infos npc_id="210133"  var_id="0" max_kill="3"/>
		<monster_infos npc_id="210134"  var_id="0" max_kill="3"/>
		<monster_infos npc_id="210705"  var_id="0" max_kill="3"/>
	</monster_hunt>

	<!-- Prologue handled by script -->

	<!-- Sleeping on the Job -->
	<report_to id="1101" start_npc_id="203049" end_npc_id="203057"/>

	<!-- Collecting Aria -->
	<item_collecting id="1206" start_npc_id="203059" />

	<!-- Grain Thieves -->
	<item_collecting id="1103" start_npc_id="203057" action_item_id="700105" />
	
	<!-- Report to Polina -->
	<report_to id="1104" start_npc_id="203057" end_npc_id="203059"/>
	
	<!-- The Snuffler Headache -->
	<item_collecting id="1105" start_npc_id="203050" />
	
	<!-- A New Skill handled by script-->
	
	<!-- Abandoned Goods -->
	<item_collecting id="1109" start_npc_id="798007" action_item_id="700106" />

	<!-- Helping Kales -->
	<report_to id="1106" start_npc_id="203050" end_npc_id="203061" item_id="182200203"/>
	
	<!-- The Kerub Threat handled by script -->

	<!-- The Lost Axe handled by script -->

	<!-- Unos Ingredients -->
	<item_collecting id="1108" start_npc_id="203061" />
	
	<!-- A Book for Namus -->
	<report_to id="1110" start_npc_id="203065" end_npc_id="203075" item_id="182200206"/>
	
	<!-- Insomnia Medicine handled by script -->
	
	<!-- Mushroom Thieves -->
	<monster_hunt id="1113" start_npc_id="203076">
		<monster_infos npc_id="210262"  var_id="0" max_kill="8"/>
		<monster_infos npc_id="210675"  var_id="0" max_kill="8"/>
	</monster_hunt>
	
	<!-- To Fish in Peace -->
	<monster_hunt id="1112" start_npc_id="203072">
		<monster_infos npc_id="210259"  var_id="0" max_kill="5"/>
		<monster_infos npc_id="210672"  var_id="0" max_kill="5"/>
		<monster_infos npc_id="210065"  var_id="1" max_kill="5"/>
		<monster_infos npc_id="210066"  var_id="1" max_kill="5"/>
	</monster_hunt>
	
	<!-- Request of the Elim handled by script -->
	
	<!-- The Elim's Message handled by script -->

	<!-- The Nymph's Gown handled by script -->
	
	<!-- A Taste of Namus's Medicine -->
	<report_to id="1119" start_npc_id="203075" end_npc_id="203080" item_id="182200225"/>
	
	<!-- Light up the Night -->
	<item_collecting id="1117" start_npc_id="203074" />
	
	<!-- Pernos's Robe -->
	<item_collecting id="1116" start_npc_id="203060" />
	
	<!-- Polinia's Ointment -->
	<report_to id="1118" start_npc_id="203059" end_npc_id="203079" item_id="0"/>
	
	<!-- Thinning out Worgs -->
	<monster_hunt id="1120" start_npc_id="203082">
		<monster_infos npc_id="210143"  var_id="0" max_kill="9"/>
		<monster_infos npc_id="210142"  var_id="0" max_kill="9"/>
	</monster_hunt>
	
	<!-- Handle by Script Ancient Cube -->
	
	<!-- Avenging Tutty -->
	<item_collecting id="1124" start_npc_id="790001" />
	
	<!-- Delivering Pernos's Robe handled by script -->
	
	<!-- Illegal Logging handled by script -->
	
	<!-- Oz's Prayer Beads -->
	<item_collecting start_npc_id="203081" id="1121"/>
	
	<!-- Where's Tutty? handled by script -->
	
	<!-- Mushroom Research -->
	<item_collecting start_npc_id="203079" id="1126"/>
	
	<!-- Neutralizing Odium handled by script -->
	
	<!-- Suspicious Ore -->
	<item_collecting id="1125" start_npc_id="203085" action_item_id="700107" />
	
	<!-- Tula's Music Box -->
	<item_collecting start_npc_id="203082" end_npc_id="203085" id="1207"/>

	<!-- Barring the Gate handled by script -->
	
	<!-- Scouting Timolia Mine -->
	<item_collecting start_npc_id="203085" id="1129"/>
	
	
</quest_scripts>
